title: Aviation Oversight Atlas
description: Country-by-country directory of aviation safety oversight authorities
theme: jekyll-theme-leap-day

plugins:
  - jekyll-sitemap
  - jekyll-feed

# PROJECT SITE: this MUST match your repo name
baseurl: "/aviation-oversight-atlas"

<<<<<<< HEAD
show_downloads: false
google_analytics: G-39G1G2LEPY


navbar:
  links:
    - title: Home
      url: /
    - title: Countries
      url: /countries/
=======
# navbar:
#   links:
#     - title: Home
#       url: /
#     - title: Countries
#       url: /countries/
>>>>>>> 3334152 (Restore leap day template)

markdown: kramdown
kramdown:
  input: GFM

